name: Build
on: workflow_dispatch
jobs:
  build:
    name: Build

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, mac-latest ]
        java-version: [ 11, 17 ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Setup JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: adopt
          java-version: ${{ matrix.java-version }}

      - name: Set Gradle Executable
        shell: bash
        run: chmod +x gradlew

      - name: Build
        shell: bash
        run: ./gradlew build --info

      - name: Extract Version
        id: extract_version
        shell: bash
        run: |
          echo ::set-output name=version::$(./gradlew -q explorer:properties | grep ^version: | cut -d ' ' -f 2)

      - name: Run Integration Tests
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: ./gradlew integrationTest --info

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: "**/test-results/**/*.xml"

      - name: Run Headless Jar Health Test
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: ./gradlew verifyJarStarts --info

      - name: Package
        if: matrix.java-version == 17
        shell: bash
        run: ./gradlew jpackage --info

      - name: GitHub Release Installer
        if: matrix.java-version == 17
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          files: explorer/build/jpackage/*
          fail_on_unmatched_files: true

      - name: Build Cross Platform Jar
        if: matrix.java-version == 11 && matrix.os == 'ubuntu-latest'
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: |
            export FAT_JAR=true
            ./gradlew clean --info
            ./gradlew build --info
            ./gradlew integrationTest --info
            ./gradlew verifyJarStarts --info

      - name: GitHub Release Jar
        if: matrix.java-version == 11 && matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          files: explorer/build/libs/jvm-explorer-${{ steps.extract_version.outputs.version }}.jar
          fail_on_unmatched_files: true